version: '3.8'

services:
  data:
    image: mariadb:latest
    container_name: data
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - network3

  script:
    build: ./php
    container_name: script
    volumes:
      - ./app:/app
    depends_on:
      - data
    networks:
      - network3

  http:
    image: nginx:latest
    container_name: http
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - script
    networks:
      - network3

networks:
  network3:
    driver: bridge
